alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: frontend-ourbnb
      match:
        path:
          prefix: /
name: ourbnb-frontend
region: nyc
services:
  - http_port: 8080
    image:
      deploy_on_push:
        enabled: true
      registry_type: DOCR
      repository: frontend-ourbnb
      tag: latest
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    name: frontend-ourbnb
