name: deploy

on: 
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml' 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint: 
    runs-on: ubuntu-22.04
    steps: 
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: install dependencies
        run: npm ci
        working-directory: ./frontend
      - name: lint
        run: npm run lint
        working-directory: ./frontend
        
  build-image:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps: 
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: log in to DigitalOcean Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: registry.digitalocean.com
          username: do
          password: ${{ secrets.DIGITALOCEAN_API_KEY }}
      - name: build and push image
        id: push
        uses: docker/build-push-action@v6.5.0
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: registry.digitalocean.com/ourbnb/frontend-ourbnb:latest
      - name: Deploy the app
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_API_KEY }}
