name: deploy

on: 
  push:
    branches:  [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint: 
    runs-on: ubuntu-22.04
    steps: 
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
        
  build:
    runs-on: ubuntu-22.04
    steps: 
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
    
